name: Check lua formatting
on: [push]
jobs:
  stylua:
    - uses: actions/checkout@v4
    - uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v2.1.0
        args: --check .
